server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/solidapp
    username: root
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    serialization:
      write-dates-as-timestamps: false

logging:
  level:
#    org.springframework.security: DEBUG
    com.solid.auth : DEBUG

#jwt:
#  secret: your-secret-key
#  expiration-time: 86400000